In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import pandas as pd 
from tensorpotential.utils.utilities import generate_tp_atoms
from ase.calculators.singlepoint import SinglePointCalculator

In [5]:
df = pd.read_pickle('./Cu_df1_A1_A2_A3_EV_elast_phon.pckl.gzip', compression="gzip")

cutoff = 3

def do_tp_atoms(row):
    at = row['ase_atoms']
    en = row['energy_corrected']
    f = row['forces']
    calc = SinglePointCalculator(at, energy=en, forces=f)
    at.set_calculator(calc)     # attaches calculator object to atoms 
    
    return generate_tp_atoms(at, cutoff=cutoff)

In [12]:
row = df.iloc[2]
at = row['ase_atoms']
at.get_positions()

array([[4.33680869e-19, 7.07100000e-03, 7.07100000e-03],
       [3.33066907e-16, 1.81563000e+00, 1.81563000e+00],
       [7.26251800e+00, 1.08937770e+01, 3.63125900e+00],
       [7.26251800e+00, 1.27094070e+01, 5.44688900e+00],
       [1.81563000e+00, 0.00000000e+00, 1.81563000e+00],
       [1.81563000e+00, 1.81563000e+00, 3.63125900e+00],
       [9.07814800e+00, 1.08937770e+01, 5.44688900e+00],
       [1.81563000e+00, 5.44688900e+00, 7.26251800e+00],
       [3.63125900e+00, 0.00000000e+00, 3.63125900e+00],
       [1.08937770e+01, 9.07814800e+00, 5.44688900e+00],
       [1.08937770e+01, 1.08937770e+01, 7.26251800e+00],
       [1.08937770e+01, 1.27094070e+01, 9.07814800e+00],
       [5.44688900e+00, 0.00000000e+00, 5.44688900e+00],
       [5.44688900e+00, 1.81563000e+00, 7.26251800e+00],
       [1.27094070e+01, 1.08937770e+01, 9.07814800e+00],
       [5.44688900e+00, 5.44688900e+00, 1.08937770e+01],
       [1.81563000e+00, 1.81563000e+00, 0.00000000e+00],
       [1.81563000e+00, 3.63125

In [10]:
from ase.neighborlist import NewPrimitiveNeighborList

nghbrs_lst = NewPrimitiveNeighborList(cutoffs=[cutoff * 0.5] * len(atoms), skin=0,
                                          self_interaction=False, bothways=True, use_scaled_positions=True)

print(nghbrs_lst)

In [10]:
import tensorflow as tf 
import numpy as np

r_ij = tf.constant(np.random.randn(6).reshape(2, 3))

d_ij = tf.reshape(tf.linalg.norm(r_ij, axis=1), [-1, 1])
rhat = r_ij / d_ij  # [None, 3]/[None, 1] -> [None, 3]

print(r_ij)
print(d_ij)
print(rhat) 

tf.Tensor(
[[-0.05648739  0.78385696  0.58151072]
 [ 1.10322333 -0.5805956  -0.2407384 ]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[0.97763863]
 [1.26970388]], shape=(2, 1), dtype=float64)
tf.Tensor(
[[-0.05777941  0.801786    0.59481153]
 [ 0.86888238 -0.45726851 -0.189602  ]], shape=(2, 3), dtype=float64)
